export const data = [
  {
    question: "Which language runs in a web browser?",
    a: "Java",
    b: "C",
    c: "Python",
    d: "JavaScript",
    correct: "d",
  },
  {
    question: "What does CSS stand for?",
    a: "Central Style Sheets",
    b: "Cascading Style Sheets",
    c: "Cascading Simple Sheets",
    d: "Cars SUVs Sailboats",
    correct: "b",
  },
  {
    question: "What does HTML stand for?",
    a: "Hypertext Markup Language",
    b: "Hypertext Markdown Language",
    c: "Hyperloop Machine Language",
    d: "Helicopters Terminals Motorboats Lamborginis",
    correct: "a",
  },
  {
    question: "What year was JavaScript launched?",
    a: "1996",
    b: "1995",
    c: "1994",
    d: "none of the above",
    correct: "b",
  },
  {
    question: "Which tag is used to define an unordered list in HTML?",
    a: "<ul>",
    b: "<ol>",
    c: "<li>",
    d: "<list>",
    correct: "a",
  },
  {
    question: "Which property is used to change the text color in CSS?",
    a: "font-color",
    b: "text-color",
    c: "color",
    d: "background-color",
    correct: "c",
  },
  {
    question: "Inside which HTML element do we put the JavaScript code?",
    a: "<js>",
    b: "<javascript>",
    c: "<script>",
    d: "<code>",
    correct: "c",
  },
  {
    question: "Which HTML attribute is used to define inline styles?",
    a: "font",
    b: "class",
    c: "style",
    d: "styles",
    correct: "c",
  },
  {
    question: "Which CSS property controls the text size?",
    a: "font-size",
    b: "text-size",
    c: "font-style",
    d: "text-style",
    correct: "a",
  },
  {
    question: "How do you write 'Hello World' in an alert box in JavaScript?",
    a: "msgBox('Hello World');",
    b: "alertBox('Hello World');",
    c: "msg('Hello World');",
    d: "alert('Hello World');",
    correct: "d",
  },
  {
    question: "Which HTML tag is used to make text bold?",
    a: "<bold>",
    b: "<b>",
    c: "<strong>",
    d: "Both b and strong",
    correct: "d",
  },
  {
    question: "Which symbol is used for comments in JavaScript?",
    a: "//",
    b: "<!-- -->",
    c: "/* */",
    d: "#",
    correct: "a",
  },
  {
    question: "How can you apply a style to all <p> elements in CSS?",
    a: "p {}",
    b: ".p {}",
    c: "#p {}",
    d: "*p {}",
    correct: "a",
  },
  {
    question: "Which method is used to get an element by ID in JavaScript?",
    a: "getElement(id)",
    b: "getElementById()",
    c: "querySelectorById()",
    d: "getById()",
    correct: "b",
  },
  {
    question: "Which value of the position property makes an element sticky?",
    a: "absolute",
    b: "fixed",
    c: "relative",
    d: "sticky",
    correct: "d",
  },
  {
    question: "Which event occurs when the user clicks on an HTML element?",
    a: "onchange",
    b: "onclick",
    c: "onmouseclick",
    d: "onmouseover",
    correct: "b",
  },
  {
    question: "Which property is used to change the background color?",
    a: "bgcolor",
    b: "background-color",
    c: "color-background",
    d: "bg-color",
    correct: "b",
  },
  {
    question: "Which input type is used to enter an email in HTML?",
    a: "type='text'",
    b: "type='email'",
    c: "type='mail'",
    d: "type='input'",
    correct: "b",
  },
  {
    question: "What does DOM stand for?",
    a: "Document Object Model",
    b: "Data Object Model",
    c: "Document Order Model",
    d: "Desktop Object Model",
    correct: "a",
  },
  {
    question: "Which HTML element is used to create a line break?",
    a: "<br>",
    b: "<lb>",
    c: "<break>",
    d: "<line>",
    correct: "a",
  },
];
